// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw15PZmjvazKTUMK3yAVuIxzJlE4uauBA',
    appId: '1:683859487460:web:7c3dac85bfdfd260811af1',
    messagingSenderId: '683859487460',
    projectId: 'booktable-47252',
    authDomain: 'booktable-47252.firebaseapp.com',
    databaseURL: 'https://booktable-47252-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'booktable-47252.firebasestorage.app',
    measurementId: 'G-7SFE3244F2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyAd9ikNCdzad8QtwAxhTb8TWGDhh1s9A',
    appId: '1:683859487460:android:c96eb6ef09ea6735811af1',
    messagingSenderId: '683859487460',
    projectId: 'booktable-47252',
    databaseURL: 'https://booktable-47252-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'booktable-47252.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW6z-8BjQVkKx4JMP0gr7dStBecW-P0JE',
    appId: '1:683859487460:ios:9969261da06e9176811af1',
    messagingSenderId: '683859487460',
    projectId: 'booktable-47252',
    databaseURL: 'https://booktable-47252-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'booktable-47252.firebasestorage.app',
    iosBundleId: 'com.example.orderNowAndroid',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW6z-8BjQVkKx4JMP0gr7dStBecW-P0JE',
    appId: '1:683859487460:ios:9969261da06e9176811af1',
    messagingSenderId: '683859487460',
    projectId: 'booktable-47252',
    databaseURL: 'https://booktable-47252-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'booktable-47252.firebasestorage.app',
    iosBundleId: 'com.example.orderNowAndroid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw15PZmjvazKTUMK3yAVuIxzJlE4uauBA',
    appId: '1:683859487460:web:c299c52ec510a1dd811af1',
    messagingSenderId: '683859487460',
    projectId: 'booktable-47252',
    authDomain: 'booktable-47252.firebaseapp.com',
    databaseURL: 'https://booktable-47252-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'booktable-47252.firebasestorage.app',
    measurementId: 'G-NF8FCPZWCP',
  );

}